[".zsh/plugins/zsh-autoswitch-virtualenv"]
    type = "archive"
    url = "https://github.com/MichaelAquilina/zsh-autoswitch-virtualenv/archive/refs/heads/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
