# macOS-only brew assets: casks, vscode extensions, taps, and formulae that
# don't have a clean apt equivalent. Cross-platform CLI formulae live in
# packages/common.txt — this file is just the bits the Brewfile DSL is
# uniquely good at, plus mac-only stuff.

brew "act"
brew "blueutil"
brew "chezmoi"
brew "copier"
brew "coreutils"
brew "csvkit"
brew "delve"
brew "devcontainer"
brew "eza"
brew "git-delta"
brew "go"
brew "gopls"
brew "lazygit"
brew "markdownlint-cli"
brew "mas"
brew "node"
brew "podlet"
brew "prettier"
brew "pyenv"
brew "python@3.13"
brew "python@3.14"
brew "railway"
brew "redis", restart_service: :changed
brew "tfenv"
brew "uv"
brew "vale"
brew "watch"
brew "weasyprint"
brew "wget"
brew "xsv"
brew "yq"

cask "basictex"
cask "flux-app"
cask "font-commit-mono"
cask "font-geist-mono"
cask "font-ibm-plex-mono"
cask "font-iosevka"
cask "font-jetbrains-mono"
cask "font-maple-mono"
cask "font-monaspace"
cask "font-monaspice-nerd-font"
cask "gcloud-cli"
cask "google-chrome"
cask "google-drive"
cask "orbstack"
cask "tailscale-app"
cask "vlc"

# Mac App Store apps are managed in mas.txt + .chezmoiscripts/run_onchange_after_install-mas-apps.sh.tmpl
vscode "aaron-bond.better-comments"
vscode "anthropic.claude-code"
vscode "bierner.markdown-mermaid"
vscode "chrischinchilla.vale-vscode"
vscode "davidanson.vscode-markdownlint"
vscode "donjayamanne.githistory"
vscode "donjayamanne.python-extension-pack"
vscode "esbenp.prettier-vscode"
vscode "foxundermoon.shell-format"
vscode "github.copilot-chat"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "gruntfuggly.todo-tree"
vscode "hashicorp.terraform"
vscode "kevinrose.vsc-python-indent"
vscode "mechatroner.rainbow-csv"
vscode "ms-azuretools.vscode-containers"
vscode "ms-playwright.playwright"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpp-devtools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.vscode-speech"
vscode "qufiwefefwoyn.kanagawa"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "sainnhe.gruvbox-material"
vscode "stkb.rewrap"
vscode "streetsidesoftware.code-spell-checker"
vscode "timonwong.shellcheck"
vscode "tomoki1207.pdf"
vscode "usernamehw.errorlens"
vscode "yzhang.markdown-all-in-one"
