# macOS-only brew assets: casks, vscode extensions, taps, and formulae that
# don't have a clean apt equivalent. Cross-platform CLI formulae live in
# packages/common.txt — this file is just the bits the Brewfile DSL is
# uniquely good at, plus mac-only stuff.

brew "act"
brew "blueutil"
brew "chezmoi"
brew "copier"
brew "coreutils"
brew "csvkit"
brew "delve"
brew "devcontainer"
brew "eza"
brew "git-delta"
brew "go"
brew "gopls"
brew "lazygit"
brew "markdownlint-cli"
brew "mas"
brew "node"
brew "podlet"
brew "prettier"
brew "pyenv"
brew "python@3.13"
brew "python@3.14"
brew "railway"
brew "redis", restart_service: :changed
brew "tfenv"
brew "uv"
brew "vale"
brew "watch"
brew "weasyprint"
brew "wget"
brew "xsv"
brew "yq"

cask "1password-cli"
cask "basictex"
cask "flux-app"
cask "font-commit-mono"
cask "font-geist-mono"
cask "font-ibm-plex-mono"
cask "font-iosevka"
cask "font-jetbrains-mono"
cask "font-maple-mono"
cask "font-monaspace"
cask "font-monaspice-nerd-font"
cask "gcloud-cli"
cask "google-chrome"
cask "google-drive"
cask "orbstack"
cask "tailscale-app"
cask "vlc"

# Mac App Store apps are managed in mas.txt + .chezmoiscripts/run_onchange_after_install-mas-apps.sh.tmpl
